/**
 * Frontend type definitions for Discussion — mirrors backend/src/domain/discussion.ts
 */

/** The lifecycle status of a discussion. */
export type DiscussionStatus = "active" | "finished" | "stopped" | "paused";

/** A roundtable discussion. */
export interface Discussion {
  /** Unique identifier generated by the application. */
  id: string;
  /** The title / topic of the discussion. */
  title: string;
  /** Current lifecycle status. New discussions start as "active". */
  status: DiscussionStatus;
  /** ISO 8601 timestamp of when the discussion was created. */
  createdAt: string;
  /** Duration limit in seconds (60/180/300). */
  durationLimit: number;
}

/** UI-specific display state for a discussion card. */
export type DiscussionDisplayStatus = "waiting" | "running" | "finished";

/** Maps backend DiscussionStatus to UI display status. */
export function toDisplayStatus(status: DiscussionStatus): DiscussionDisplayStatus {
  switch (status) {
    case "active":
      return "running";
    case "finished":
      return "finished";
    case "stopped":
      return "finished";
    case "paused":
      return "finished";
  }
}
