/**
 * Frontend type definitions for Message — mirrors backend/src/domain/message.ts
 */

/** The role of a message author. */
export type MessageRole = "user" | "assistant";

/**
 * The conversational function of a message in the discussion transcript.
 * Service-generated trusted metadata — not accepted from untrusted clients.
 */
export type MessageKind =
  | "moderator_opening"
  | "moderator_call"
  | "moderator_closing"
  | "expert_statement"
  | "system_notification";

/**
 * A single message belonging to a discussion.
 */
export interface Message {
  /** Unique identifier generated by the application. */
  id: string;
  /** The discussion this message belongs to. */
  discussionId: string;
  /**
   * The panelist who authored this message, or null when the message
   * was not produced by a panelist (system notification, legacy message,
   * or lifecycle boundary marker).
   */
  panelistId: string | null;
  /** Whether the message was sent by the user or an AI assistant. */
  role: MessageRole;
  /**
   * The conversational function this message serves in the transcript,
   * or null for messages created before this field existed.
   */
  kind: MessageKind | null;
  /** The text content of the message. */
  content: string;
  /**
   * The id of the prior Message this message directly responds to,
   * or null when this message is not a reply.
   */
  replyToMessageId: string | null;
  /** ISO 8601 timestamp of when the message was created. */
  createdAt: string;
}

/** UI label mapping for message kinds (Chinese). */
export const MESSAGE_KIND_LABELS: Record<MessageKind, string> = {
  moderator_opening: "开场",
  moderator_call: "主持",
  moderator_closing: "总结",
  expert_statement: "发言",
  system_notification: "系统",
};
