/** The lifecycle status of a discussion. */
export type DiscussionStatus = "active" | "finished" | "stopped" | "paused";

/** A roundtable discussion. */
export interface Discussion {
  /** Unique identifier generated by the application. */
  id: string;
  /** The title / topic of the discussion. */
  title: string;
  /** Current lifecycle status. New discussions start as "active". */
  status: DiscussionStatus;
  /** ISO 8601 timestamp of when the discussion was created. */
  createdAt: string;
  /** Duration limit in seconds (60/180/300), default 300. */
  durationLimit: number;
}

/** The data required to create a new Discussion. */
export interface CreateDiscussionInput {
  title: string;
  /** Duration limit in seconds (60/180/300), default 300. */
  durationLimit?: number;
}
