/** The lifecycle status of a discussion. */
export type DiscussionStatus = "active" | "finished";

/** A roundtable discussion. */
export interface Discussion {
  /** Unique identifier generated by the application. */
  id: string;
  /** The title / topic of the discussion. */
  title: string;
  /** Current lifecycle status. New discussions start as "active". */
  status: DiscussionStatus;
  /** ISO 8601 timestamp of when the discussion was created. */
  createdAt: string;
}

/** The data required to create a new Discussion. */
export interface CreateDiscussionInput {
  title: string;
}
