/** The role of a message author. */
export type MessageRole = "user" | "assistant";

/**
 * The conversational function of a message in the discussion transcript.
 *
 * These values are **service-generated trusted metadata**.  They must not
 * be accepted as identity claims from untrusted clients.  Only server-side
 * components (RoundController, ModeratorStrategy, lifecycle implementations)
 * may set these fields through {@link MessageRepository.create}.
 */
export type MessageKind =
  | "moderator_opening"
  | "moderator_call"
  | "moderator_closing"
  | "expert_statement"
  | "system_notification";

/**
 * A single message belonging to a discussion.
 *
 * The three metadata fields have independent meanings:
 *
 * - `panelistId` — WHO produced the message (null for system messages)
 * - `kind` — WHAT conversational function this record serves
 * - `replyToMessageId` — WHAT prior message this responds to
 */
export interface Message {
  /** Unique identifier generated by the application. */
  id: string;
  /** The discussion this message belongs to. */
  discussionId: string;
  /**
   * The panelist who authored this message, or null when the message
   * was not produced by a panelist (system notification, legacy message,
   * or lifecycle boundary marker).
   *
   * Service-generated — not accepted from untrusted client input.
   */
  panelistId: string | null;
  /** Whether the message was sent by the user or an AI assistant. */
  role: MessageRole;
  /**
   * The conversational function this message serves in the transcript,
   * or null for messages created before this field existed.
   *
   * Service-generated — not accepted from untrusted client input.
   */
  kind: MessageKind | null;
  /** The text content of the message. */
  content: string;
  /**
   * The id of the prior {@link Message} this message directly responds to,
   * or null when this message is not a reply (opening statement, moderator
   * bridge, system notification, lifecycle marker).
   *
   * Service-generated — not accepted from untrusted client input.
   */
  replyToMessageId: string | null;
  /** ISO 8601 timestamp of when the message was created. */
  createdAt: string;
}

/** The data required to create a new Message. */
export interface CreateMessageInput {
  discussionId: string;
  role: MessageRole;
  content: string;
  /**
   * Service-generated — not accepted from untrusted client input.
   * Defaults to null when omitted.
   */
  panelistId?: string | null;
  /**
   * Service-generated — not accepted from untrusted client input.
   * Defaults to null when omitted.
   */
  kind?: MessageKind | null;
  /**
   * Service-generated — not accepted from untrusted client input.
   * Defaults to null when omitted.
   */
  replyToMessageId?: string | null;
}
