/** The role of a message author. */
export type MessageRole = "user" | "assistant";

/** A single message belonging to a discussion. */
export interface Message {
  /** Unique identifier generated by the application. */
  id: string;
  /** The discussion this message belongs to. */
  discussionId: string;
  /** Whether the message was sent by the user or an AI assistant. */
  role: MessageRole;
  /** The text content of the message. */
  content: string;
  /** ISO 8601 timestamp of when the message was created. */
  createdAt: string;
}

/** The data required to create a new Message. */
export interface CreateMessageInput {
  discussionId: string;
  role: MessageRole;
  content: string;
}
