/** The role of a panelist — either the discussion host or an expert. */
export type PanelistRole = "host" | "expert";

/** The current state of a panelist during a discussion. */
export type PanelistStatus =
  | "waiting"
  | "raising_hand"
  | "preparing"
  | "speaking"
  | "finished";

/** A panelist (host or expert) participating in a discussion. */
export interface Panelist {
  /** Unique identifier generated by the application. */
  id: string;
  /** The discussion this panelist belongs to. */
  discussionId: string;
  /** Whether this panelist is the host or an expert. */
  role: PanelistRole;
  /** Display name. */
  name: string;
  /** Profession / occupation. */
  occupation: string;
  /** Job title or role description. */
  title: string;
  /** The panelist's stance or viewpoint on the topic. */
  stance: string;
  /** Core beliefs driving this expert's worldview (1-2 sentences, Chinese). */
  beliefs: string | null;
  /** Specific concerns or fears related to the topic (1-2 sentences, Chinese). */
  concerns: string | null;
  /** Argumentation style, e.g. "数据驱动", "激进反驳", "温和建设". */
  argumentStyle: string | null;
  /** A CSS-compatible color used as a visual identifier. */
  color: string;
  /** Current state in the discussion lifecycle. */
  status: PanelistStatus;
  /** What the panelist is currently focusing on, or null. */
  currentFocus: string | null;
  /** A short public summary of the panelist's current thinking, or null. */
  publicSummary: string | null;
  /** ISO 8601 timestamp of when the panelist was created. */
  createdAt: string;
  /** ISO 8601 timestamp of last speaking turn, null if never spoken. */
  lastSpokeAt: string | null;
  /** Number of speaking turns completed so far. */
  speakCount: number;
}

/** The data required to create a new Panelist. */
export interface CreatePanelistInput {
  discussionId: string;
  role: PanelistRole;
  name: string;
  occupation: string;
  title: string;
  stance: string;
  color: string;
  /** Core beliefs (1-2 sentences, Chinese). */
  beliefs?: string | null;
  /** Specific concerns (1-2 sentences, Chinese). */
  concerns?: string | null;
  /** Argumentation style. */
  argumentStyle?: string | null;
}
